FROM python:3.6.1-alpine
COPY . /mysql-parser/
RUN sed -i 's/dl-cdn.alpinelinux.org/mirror.tuna.tsinghua.edu.cn/g' /etc/apk/repositories &&\
    apk add --no-cache mariadb-dev g++ && \
    pip install --no-cache-dir -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com -r /mysql-parser/requirements.txt && \
    apk del g++ mariadb-dev && \
    apk add --no-cache mariadb-client-libs

WORKDIR /mysql-parser/parser
CMD ["python", "run_server.py"]
